name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout main branch
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        cache: maven
        
    - name: Run Java version
      run: java --version  
      
    - name: Run maven version
      run: mvn -v
      
    - name: Check current directory
      run: ls -a
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Check target dir
      run: |
        cd target
        ls -a
